### ISSUE TITLE
"Build and run current file" causes NPE when used on an empty file

### ISSUE THREAD

**Issue by 5hir0kur0** [5hir0kur0/B8E#8]
__Steps to reproduce:__
1.  Click "File" > "New"
2.  Click "Project" > "Build and run current file"

__Result:__
`NullPointerException `
(
```
java.lang.NullPointerException
        at gui.MainWindow$23.actionPerformed(MainWindow.java:977)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
[...]
```
)

__Suggested behavior:__
Ask the user to save the file and then build and run it.

**Comment by 5hir0kur0** [comment]
For me, it keeps causing NPEs even after saving the file to disk.

**Comment by 5hir0kur0** [comment]
Even opening a already saved file ("demo.asm") and clicking "Build and run current file" caused an NPE (there was Problem output though, so the assembler must have run).

Now "Build and run current file" is grayed out and I cannot click it…
